### ISSUE TITLE
Takeover maintainership of movfs4l.py

### ISSUE THREAD

**Issue by ajventer** [qsniyg/winevfs#2]
Hi,
As you know I've not really committed much to that script in recent months, just moderated what comes in from other people, and the overwhelming majority came from you.
I'm not using MO2 anymore myself, vortex works well under wine now and I am quite happy with it, the only significant downside is that it's windows symlinks aren't created as symlinks on Linux, and in fact are copies - so it uses more diskspace but I'm happy with it. I really don't have the free time to maintain it anymore. It was really just a way I came up with back then to be able to mod my skyrim/fallout games - I never thought of it as a very serious project.

So since I'm not actually using the script, I'm really not motivated to maintain it. Since you are using it, and improving it constantly, would you like to take over as official maintainer ? I'd gladly hand the reigns over to you - you may well know the code as  it stands today better than I do !

**Comment by qsniyg** [comment]
Absolutely, and thank you so much for initially creating the script! :)

It is interesting timing though, as I believe I've nearly solved the issue of running USVFS under wine! I've already got Fallout 4 working, and I _believe_ all that's left is one more issue to solve. Of course, everything is more complicated than it initially seems, so I might still be a week or so away from completion, but it might be sooner. Hopefully!

**Comment by ajventer** [comment]
Heh, so it may actually be unimportant in the near future. 

Either way, I'm glad it was there when it was needed. I tried to do a repo transfer however, and I can;'t because you have a forked version of the repo in your account which causes a namespace clash.

**Comment by qsniyg** [comment]
@ajventer Ah okay, deleted. By the way, if you're doing it this way, would you mind creating a new blank ksp_stuff repo under your account linking to the transferred one (and maybe create a fake movfs4l.py as well)? That way existing links to your repo won't be broken (otherwise it'll likely be frustrating for new users to find the tool).

**Comment by ajventer** [comment]
Good call, I'll do that.

**Comment by qsniyg** [comment]
~~Weird, it says the repository transfer has expired.~~ Seems to have worked.
